# Lecture 18
options(prompt = "R>")
# Lecture 18 Building the Query
dbGetQuery(PSTAT10db, 'SELECT * FROM DEPARTMENT')
dbGetQuery(PSTAT10db, 'SELECT * FROM EMPLOYEE')

# Coding
dbGetQuery(PSTAT10db, 'SELECT EMP_NO,EMPLOYEE.NAME, DEPARTMENT.NAME FROM EMPLOYEE INNER JOIN DEPARTMENT WHERE NOT (MANAGER == "null")')



#CODDING WITH CORRELATION NAMES
dbGetQuery(PSTAT10db, 'SELECT DISTINCT C.NAME, P.NAME AS ProductName, COLOR AS RequiredColor
FROM CUSTOMER C, SALES_ORDER_LINE O, SALES_ORDER S, PRODUCT P WHERE C.CUST_NO = S.CUST_NO
AND S.ORDER_NO = O.ORDER_NO
AND O.PROD_NO = P.PROD_NO
AND C.NAME = "ALEX"')
